/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.

*/

#include <iostream>

int main(void)
{
  using namespace std;
  long long maxVal = 4000000;
  long long sum = 0;
 
  long long prevFib = 1;
  long long curFib = 2;

  cout << "sizeof(long long) " << sizeof(long long) << " " << maxVal << " " << curFib << endl;

  while( curFib < maxVal )
  {
     if( 0 == (curFib & 0x1) )
     {
       sum += curFib;
     }

     long long temp = curFib;
     curFib = curFib + prevFib;
     prevFib = temp;
  }

  cout << "the sum of all the even-valued terms in the sequence which do not exceed four million is " << sum << endl;

  return 0;
}

