//
//  prob0012.h
//  ProjectEuler
//
//  Created by Benjamin Gregorski on 8/18/11.
//  Copyright 2011 __MyCompanyName__. All rights reserved.
//
 
/*

  The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
  
  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
  
  Let us list the factors of the first seven triangle numbers:
  
  1: 1
  3: 1,3
  6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28
  We can see that 28 is the first triangle number to have over five divisors.
  
  What is the value of the first triangle number to have over five hundred divisors?

*/

#ifndef _PROB_0012_H_
#define _PROB_0012_H_

void solveProb0012();

#endif

